Initial config
dbt-labs/oss-at-dbt pull request #1
Opened 2024-04-04 00:17 UTC by mikealfare

2024-04-05 15:13 UTC, emmyoop requested changes
It would be nice to have some sort of table of contents.  Similar to how the OSPO does it [here](https://github.com/todogroup/outbound-oss/blob/main/content/00-toc.md).

2024-04-05 15:13 UTC, emmyoop commented on .github/ISSUE_TEMPLATE/decision.yml
Is the idea that we would open an issue to drive public discussions and then open a PR from the outcome of the discussions?

2024-04-05 23:02 UTC, mikealfare commented on .github/ISSUE_TEMPLATE/decision.yml
I think so. That felt the most natural to me and was quick to set up. But I see this as a process that we will incrementally improve and I was only looking for a starting point. So please say so if you have a different approach you'd like to try.

2024-04-05 23:31 UTC, mikealfare commented
> It would be nice to have some sort of table of contents. Similar to how the OSPO does it [here](https://github.com/todogroup/outbound-oss/blob/main/content/00-toc.md).

I added the most basic version of this. We can always add content to it, and the TOC "generation" is currently manual.

2024-04-09 12:19 UTC, emmyoop approved these changes

2024-04-12 05:50 UTC, merged